const C=window.ZION_CONFIG;
if(sessionStorage.getItem('zion_role')!=='admin') location.href='index.html';
const defaults={sermons:[{id:'s1',title:'Walking in Faith',speaker:'Pastor',date:'2026-09-08',description:'A message about trusting God through every season.',file:''}],events:[{id:'e1',title:'Sunday Worship Service',date:'2026-09-13',time:'[Add time]',location:'[Add location]',description:'Join us for worship, teaching and fellowship.'}],announcements:[{id:'a1',title:'Welcome to the Zion Assembly Portal',date:'2026-09-08',body:'This is your new home for sermons, announcements and church updates.'}]};
function getData(){try{const s=localStorage.getItem(C.storageKey);if(s)return JSON.parse(s)}catch(e){}localStorage.setItem(C.storageKey,JSON.stringify(defaults));return structuredClone(defaults)}
let data=getData();const save=()=>localStorage.setItem(C.storageKey,JSON.stringify(data));const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString('en-NG',{day:'numeric',month:'short',year:'numeric'});const id=()=>Date.now().toString(36);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){const a=document.getElementById('a-sermons');if(a)a.textContent=data.sermons.length;const b=document.getElementById('a-events');if(b)b.textContent=data.events.length;const c=document.getElementById('a-announcements');if(c)c.textContent=data.announcements.length;
const sl=document.getElementById('admin-sermon-list');if(sl)sl.innerHTML=data.sermons.map(s=>`<div class="admin-item"><div><strong>${esc(s.title)}</strong><small>${fmt(s.date)} · ${esc(s.speaker||'No speaker')}</small></div><div><button onclick="editSermon('${s.id}')">Edit</button><button class="danger" onclick="delItem('sermons','${s.id}')">Delete</button></div></div>`).join('')||'<div class="empty-state">No sermons yet.</div>';
const el=document.getElementById('admin-event-list');if(el)el.innerHTML=data.events.map(s=>`<div class="admin-item"><div><strong>${esc(s.title)}</strong><small>${fmt(s.date)} · ${esc(s.time||'')}</small></div><div><button onclick="editEvent('${s.id}')">Edit</button><button class="danger" onclick="delItem('events','${s.id}')">Delete</button></div></div>`).join('')||'<div class="empty-state">No events yet.</div>';
const al=document.getElementById('admin-announcement-list');if(al)al.innerHTML=data.announcements.map(s=>`<div class="admin-item"><div><strong>${esc(s.title)}</strong><small>${fmt(s.date)}</small></div><div><button onclick="editAnnouncement('${s.id}')">Edit</button><button class="danger" onclick="delItem('announcements','${s.id}')">Delete</button></div></div>`).join('')||'<div class="empty-state">No announcements yet.</div>'}
window.delItem=(type,key)=>{if(confirm('Delete this item?')){data[type]=data[type].filter(x=>x.id!==key);save();render()}};
function fill(form,obj){Object.keys(obj).forEach(k=>{const el=form.elements[k];if(el)el.value=obj[k]||''})}
window.editSermon=i=>fill(document.getElementById('sermon-form'),data.sermons.find(x=>x.id===i));window.editEvent=i=>fill(document.getElementById('event-form'),data.events.find(x=>x.id===i));window.editAnnouncement=i=>fill(document.getElementById('announcement-form'),data.announcements.find(x=>x.id===i));
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function setup(formId,type,cancelId){const form=document.getElementById(formId);if(!form)return;form.onsubmit=e=>{e.preventDefault();const o=formData(form);o.id=o.id||id();const n=data[type].findIndex(x=>x.id===o.id);if(n<0)data[type].push(o);else data[type][n]=o;save();form.reset();form.elements.id.value='';render()};const cancel=document.getElementById(cancelId);if(cancel)cancel.onclick=()=>{form.reset();form.elements.id.value=''}}
setup('sermon-form','sermons','sermon-cancel');setup('event-form','events','event-cancel');setup('announcement-form','announcements','announcement-cancel');
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();const logout=document.getElementById('logout');if(logout)logout.onclick=()=>{sessionStorage.clear();location.href='index.html'};render();
